### ISSUE TITLE
Systemd compatiblity

### ISSUE THREAD

**Issue by gersilex** [Dynatrace/Dynatrace-Server-Ansible#7]
Systemd service files are missing, but on current distributions the `service` command redirects to `systemctl` and thus, Ansible's `service` module also uses systemctl.

There are no `dynaTraceServer.service` files distributed.

**Comment by pozieblo** [comment]
Most Linux distributions have sysv init script compatibility mode. In this mode the *.service file should be automatically generated (see for example https://www.turnkeylinux.org/blog/debugging-systemd-sysv-init-compat). Sometimes this mechanism does not work. We had such issue on Red Hat 7.2. In our case it was a Red Hat bug described here: https://bugzilla.redhat.com/show_bug.cgi?id=1285492. The solution was to update the system i.e. `yum update -y`. Please let us know if it helps

**Comment by gersilex** [comment]
Thanks for your fast answer. Ideed `/lib/systemd/system-generators/systemd-sysv-generator` did not run (It usually runs when reloading the configs and on boot).

Manually running `/lib/systemd/system-generators/systemd-sysv-generator` solved the issue. Btw. On our systems, Debian 8.7 at this time, this is part of the package `systemd` and requires no additional packages.

This is indeed no issue of this role, as one can rely on packages, that are installed by default. I will address this issue on the systemd/debian site now. Thanks!
